version: '3.8'

services:
  ai-terminal-backend:
    image: aixier/ai-terminal-backend:latest
    container_name: ai-terminal-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your-production-jwt-secret-change-this
    volumes:
      - backend_logs:/app/logs
      - backend_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  ai-terminal-ui:
    image: aixier/ai-terminal-ui:latest
    container_name: ai-terminal-ui
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - API_TARGET=http://ai-terminal-backend:3000
    depends_on:
      - ai-terminal-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_logs:
    driver: local
  backend_data:
    driver: local

networks:
  default:
    name: ai-terminal-network