<template>
  <div class="card-download-step">
    <div class="step-header">
      <h2 class="step-title">🎉 卡片生成完成！</h2>
      <p class="step-description">
        您的知识卡片已经准备就绪，选择下载格式或直接分享到社交媒体
      </p>
    </div>

    <div class="download-container">
      <!-- 最终预览 -->
      <div class="final-preview">
        <div class="preview-wrapper">
          <div class="card-final">
            <div class="card-content">
              <h3>您的知识卡片</h3>
              <p>专业生成的知识分享卡片，已优化用于社交媒体分享</p>
              <div class="card-footer">
                <span>Generated by AI Knowledge Card Creator</span>
              </div>
            </div>
          </div>
        </div>
        
        <div class="preview-info">
          <div class="info-item">
            <span class="info-label">尺寸</span>
            <span class="info-value">1200x800px</span>
          </div>
          <div class="info-item">
            <span class="info-label">格式</span>
            <span class="info-value">PNG, JPG, PDF</span>
          </div>
          <div class="info-item">
            <span class="info-label">适用平台</span>
            <span class="info-value">Instagram, Twitter, 微博</span>
          </div>
        </div>
      </div>

      <!-- 下载选项 -->
      <div class="download-options">
        <h3 class="options-title">下载选项</h3>
        
        <div class="format-grid">
          <div 
            v-for="format in downloadFormats" 
            :key="format.id"
            class="format-card"
            :class="{ selected: selectedFormats.includes(format.id) }"
            @click="toggleFormat(format.id)"
          >
            <div class="format-icon">
              <el-icon><component :is="format.icon" /></el-icon>
            </div>
            <div class="format-info">
              <div class="format-name">{{ format.name }}</div>
              <div class="format-desc">{{ format.description }}</div>
              <div class="format-size">{{ format.size }}</div>
            </div>
            <div class="format-check" v-if="selectedFormats.includes(format.id)">
              <el-icon><Check /></el-icon>
            </div>
          </div>
        </div>

        <div class="quality-selector">
          <div class="quality-label">图片质量</div>
          <el-slider 
            v-model="quality" 
            :min="60" 
            :max="100" 
            show-input
            :format-tooltip="(val) => `${val}%`"
          />
        </div>

        <div class="download-actions">
          <FluentButton 
            variant="primary" 
            size="large"
            :loading="isDownloading"
            @click="downloadSelected"
            class="download-button fluent-glow-hover"
          >
            <template #icon><Download /></template>
            {{ selectedFormats.length > 1 ? `下载 ${selectedFormats.length} 个文件` : '下载' }}
          </FluentButton>
          
          <FluentButton 
            variant="subtle" 
            @click="downloadAll"
            :loading="isDownloading"
          >
            <template #icon><FolderOpened /></template>
            下载全部格式
          </FluentButton>
        </div>
      </div>

      <!-- 社交分享 -->
      <div class="share-options">
        <h3 class="options-title">直接分享</h3>
        
        <div class="share-grid">
          <div 
            v-for="platform in sharePlatforms" 
            :key="platform.id"
            class="share-card"
            @click="shareToPlatform(platform.id)"
          >
            <div class="share-icon" :style="{ backgroundColor: platform.color }">
              <el-icon><component :is="platform.icon" /></el-icon>
            </div>
            <div class="share-info">
              <div class="share-name">{{ platform.name }}</div>
              <div class="share-desc">{{ platform.description }}</div>
            </div>
            <el-icon class="share-arrow"><ArrowRight /></el-icon>
          </div>
        </div>
      </div>
    </div>

    <div class="action-buttons">
      <FluentButton variant="subtle" @click="$emit('prev')">
        <template #icon><ArrowLeft /></template>
        上一步
      </FluentButton>
      
      <div class="action-right">
        <FluentButton variant="outline" @click="saveToLibrary">
          <template #icon><BookmarkAdd /></template>
          保存到我的卡片
        </FluentButton>
        
        <FluentButton 
          variant="primary" 
          @click="$emit('restart')"
        >
          <template #icon><Plus /></template>
          创建新卡片
        </FluentButton>
      </div>
    </div>

    <!-- 下载成功提示 -->
    <el-dialog v-model="showSuccess" width="400px" align-center>
      <template #header>
        <div class="success-header">
          <el-icon class="success-icon"><Check /></el-icon>
          <span>下载完成</span>
        </div>
      </template>
      
      <div class="success-content">
        <p>您的知识卡片已成功下载到本地！</p>
        <div class="success-files">
          <div v-for="file in downloadedFiles" :key="file" class="file-item">
            <el-icon><Document /></el-icon>
            <span>{{ file }}</span>
          </div>
        </div>
      </div>
      
      <template #footer>
        <FluentButton variant="primary" @click="showSuccess = false">
          知道了
        </FluentButton>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import FluentButton from '../FluentButton.vue'
import { 
  ArrowLeft, ArrowRight, Download, FolderOpened, Check,
  Document, Picture, VideoPlay as VideoCamera, Plus, Star as BookmarkAdd,
  Platform, Promotion as Brand, Monitor
} from '@element-plus/icons-vue'
import { ElMessage, ElDialog } from 'element-plus'

const emit = defineEmits(['restart', 'prev'])

const selectedFormats = ref([1, 2]) // 默认选择PNG和JPG
const quality = ref(90)
const isDownloading = ref(false)
const showSuccess = ref(false)
const downloadedFiles = ref([])

const downloadFormats = ref([
  { 
    id: 1, 
    name: 'PNG', 
    description: '透明背景，适合设计', 
    size: '~2.5MB',
    icon: Picture 
  },
  { 
    id: 2, 
    name: 'JPG', 
    description: '体积小，适合分享', 
    size: '~800KB',
    icon: Picture 
  },
  { 
    id: 3, 
    name: 'PDF', 
    description: '矢量格式，可打印', 
    size: '~1.2MB',
    icon: Document 
  },
  { 
    id: 4, 
    name: 'SVG', 
    description: '矢量图形，可编辑', 
    size: '~150KB',
    icon: Document 
  }
])

const sharePlatforms = ref([
  { 
    id: 'instagram', 
    name: 'Instagram', 
    description: '1080x1080 正方形',
    color: '#E4405F',
    icon: Platform 
  },
  { 
    id: 'twitter', 
    name: 'Twitter', 
    description: '1200x675 横版',
    color: '#1DA1F2',
    icon: Brand 
  },
  { 
    id: 'weibo', 
    name: '微博', 
    description: '900x500 适合配图',
    color: '#E6162D',
    icon: Monitor 
  },
  { 
    id: 'linkedin', 
    name: 'LinkedIn', 
    description: '1200x627 商务分享',
    color: '#0077B5',
    icon: Brand 
  }
])

const toggleFormat = (formatId) => {
  const index = selectedFormats.value.indexOf(formatId)
  if (index > -1) {
    selectedFormats.value.splice(index, 1)
  } else {
    selectedFormats.value.push(formatId)
  }
}

const downloadSelected = async () => {
  if (selectedFormats.value.length === 0) {
    ElMessage.warning('请至少选择一种格式')
    return
  }

  isDownloading.value = true
  
  // 模拟下载过程
  try {
    await new Promise(resolve => setTimeout(resolve, 2000))
    
    downloadedFiles.value = selectedFormats.value.map(id => {
      const format = downloadFormats.value.find(f => f.id === id)
      return `knowledge-card.${format.name.toLowerCase()}`
    })
    
    showSuccess.value = true
    ElMessage.success('下载完成！')
  } catch (error) {
    ElMessage.error('下载失败，请重试')
  } finally {
    isDownloading.value = false
  }
}

const downloadAll = async () => {
  selectedFormats.value = downloadFormats.value.map(f => f.id)
  await downloadSelected()
}

const shareToPlatform = (platformId) => {
  // 分享到社交平台逻辑
  ElMessage.info(`准备分享到 ${platformId}`)
}

const saveToLibrary = () => {
  ElMessage.success('已保存到我的卡片库')
}
</script>

<style scoped>
.card-download-step {
  display: flex;
  flex-direction: column;
  gap: var(--fluent-space-xl);
}

.step-header {
  text-align: center;
}

.step-title {
  font-size: var(--fluent-font-size-hero);
  font-weight: 600;
  color: var(--fluent-neutral-primary);
  margin: 0 0 var(--fluent-space-md) 0;
  background: linear-gradient(135deg, var(--fluent-success) 0%, #51cf66 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.step-description {
  font-size: var(--fluent-font-size-lg);
  color: var(--fluent-neutral-secondary);
  margin: 0;
  max-width: 600px;
  margin: 0 auto;
}

.download-container {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: var(--fluent-space-xl);
}

/* 最终预览 */
.final-preview {
  display: flex;
  flex-direction: column;
  gap: var(--fluent-space-md);
}

.preview-wrapper {
  background: rgba(255, 255, 255, 0.8);
  border-radius: var(--fluent-radius-large);
  padding: var(--fluent-space-xl);
  display: flex;
  align-items: center;
  justify-content: center;
}

.card-final {
  width: 240px;
  height: 160px;
  background: white;
  border-radius: var(--fluent-radius-medium);
  box-shadow: var(--fluent-depth-8);
  padding: var(--fluent-space-md);
  display: flex;
  flex-direction: column;
}

.card-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  text-align: center;
}

.card-content h3 {
  font-size: var(--fluent-font-size-md);
  color: var(--fluent-neutral-primary);
  margin-bottom: var(--fluent-space-sm);
}

.card-content p {
  font-size: var(--fluent-font-size-sm);
  color: var(--fluent-neutral-secondary);
  line-height: 1.4;
}

.card-footer {
  border-top: 1px solid var(--fluent-neutral-lighter);
  padding-top: var(--fluent-space-xs);
  font-size: 10px;
  color: var(--fluent-neutral-tertiary);
  text-align: center;
}

.preview-info {
  display: flex;
  flex-direction: column;
  gap: var(--fluent-space-sm);
}

.info-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: var(--fluent-space-sm);
  background: rgba(255, 255, 255, 0.6);
  border-radius: var(--fluent-radius-medium);
}

.info-label {
  font-size: var(--fluent-font-size-sm);
  color: var(--fluent-neutral-secondary);
}

.info-value {
  font-size: var(--fluent-font-size-sm);
  font-weight: 600;
  color: var(--fluent-neutral-primary);
}

/* 下载选项 */
.download-options,
.share-options {
  display: flex;
  flex-direction: column;
  gap: var(--fluent-space-md);
}

.options-title {
  font-size: var(--fluent-font-size-lg);
  font-weight: 600;
  color: var(--fluent-neutral-primary);
  margin: 0;
}

.format-grid,
.share-grid {
  display: flex;
  flex-direction: column;
  gap: var(--fluent-space-sm);
}

.format-card,
.share-card {
  display: flex;
  align-items: center;
  gap: var(--fluent-space-md);
  padding: var(--fluent-space-md);
  background: rgba(255, 255, 255, 0.6);
  border: 2px solid transparent;
  border-radius: var(--fluent-radius-medium);
  cursor: pointer;
  transition: all var(--fluent-duration-normal) var(--fluent-easing);
  position: relative;
}

.format-card:hover,
.share-card:hover {
  background: rgba(255, 255, 255, 0.8);
  transform: translateY(-2px);
}

.format-card.selected {
  border-color: var(--fluent-blue);
  background: rgba(0, 120, 212, 0.1);
}

.format-icon,
.share-icon {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--fluent-blue);
  color: var(--fluent-neutral-white);
  font-size: 18px;
}

.format-info,
.share-info {
  flex: 1;
}

.format-name,
.share-name {
  font-weight: 600;
  color: var(--fluent-neutral-primary);
  margin-bottom: 2px;
}

.format-desc,
.share-desc {
  font-size: var(--fluent-font-size-sm);
  color: var(--fluent-neutral-secondary);
  margin-bottom: 2px;
}

.format-size {
  font-size: var(--fluent-font-size-xs);
  color: var(--fluent-neutral-tertiary);
}

.format-check {
  position: absolute;
  top: var(--fluent-space-xs);
  right: var(--fluent-space-xs);
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: var(--fluent-success);
  color: var(--fluent-neutral-white);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
}

.share-arrow {
  color: var(--fluent-neutral-tertiary);
}

.quality-selector {
  margin: var(--fluent-space-md) 0;
}

.quality-label {
  font-size: var(--fluent-font-size-sm);
  font-weight: 600;
  color: var(--fluent-neutral-primary);
  margin-bottom: var(--fluent-space-sm);
}

.download-actions {
  display: flex;
  flex-direction: column;
  gap: var(--fluent-space-sm);
}

.download-button {
  font-size: var(--fluent-font-size-md);
}

.action-buttons {
  display: flex;
  justify-content: space-between;
  padding-top: var(--fluent-space-lg);
  border-top: 1px solid rgba(255, 255, 255, 0.2);
}

.action-right {
  display: flex;
  gap: var(--fluent-space-md);
}

/* 成功对话框 */
.success-header {
  display: flex;
  align-items: center;
  gap: var(--fluent-space-sm);
}

.success-icon {
  color: var(--fluent-success);
  font-size: 20px;
}

.success-content {
  text-align: center;
}

.success-files {
  margin-top: var(--fluent-space-md);
  display: flex;
  flex-direction: column;
  gap: var(--fluent-space-xs);
}

.file-item {
  display: flex;
  align-items: center;
  gap: var(--fluent-space-xs);
  justify-content: center;
  font-size: var(--fluent-font-size-sm);
  color: var(--fluent-neutral-secondary);
}

/* 响应式调整 */
@media (max-width: 1200px) {
  .download-container {
    grid-template-columns: 1fr;
    gap: var(--fluent-space-lg);
  }
}

@media (max-width: 768px) {
  .action-buttons {
    flex-direction: column;
    gap: var(--fluent-space-md);
  }
  
  .action-right {
    justify-content: center;
  }
}
</style>